spring:
  pid:
    file: /opt/apps/ois/logs/pid.pid
  datasource:
      url: jdbc:mysql://localhost:3306/uqierp?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
      username: uplus
      password: Uplus0511
      driverClassName: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
ocs:
  order_url: http://localhost:36010/ocs/interface/orderInterface/queryByUpdateTime.do
server:
  port: 37018
